sudo: required

language: generic 

services:
  - docker

before_install:
  - docker build -t mojomojomojo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mojomojomojo/react-test npm test

after_success:
  - docker build -t mojomojomojo/multi-client ./client
  - docker build -t mojomojomojo/multi-nginx ./nginx
  - docker build -t mojomojomojo/multi-server ./server
  - docker build -t mojomojomojo/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mojomojomojo/multi-client
  - docker push mojomojomojo/multi-nginx
  - docker push mojomojomojo/multi-server
  - docker push mojomojomojo/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-ap-south-1-297338036530"
    bucket_path: "multi-docker"
    edge: true
    provider: elasticbeanstalk
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY