sudo: required

language: generic 

services:
  - docker

before_install:
  - docker build -t mojoboss/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mojoboss/react-test npm test

after_success:
  - docker build -t mojoboss/multi-client ./client
  - docker build -t mojoboss/multi-nginx ./nginx
  - docker build -t mojoboss/multi-server ./server
  - docker build -t mojoboss/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mojoboss/multi-client
  - docker push mojoboss/multi-nginx
  - docker push mojoboss/multi-server
  - docker push mojoboss/multi-worker